title: Partha Das
logo: /img/Partha_Das.jpg
description: PhD candidate in Computer Vision Lab, Informatics Institute, University of Amsterdam 
show_downloads: true
google_analytics: 
theme: jekyll-theme-minimal

