title: Partha Das
logo: /img/Partha_Das.jpg
description: PhD in Computer Vision from the Computer Vision Lab, Informatics Institute, University of Amsterdam 
show_downloads: true
google_analytics: 
theme: jekyll-theme-minimal
encoding: UTF-8
